spring.application.name=yammy

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.cloud.aws.credentials.accessKey=${AWS_ACCESS_KEY}
spring.cloud.aws.credentials.secretKey=${AWS_SECRET_KEY}
spring.cloud.aws.s3.bucket=${AWS_S3_BUCKET}
spring.cloud.aws.region.static=${AWS_REGION}
